<?php

$form->prepare();

echo $this->form()->openTag($form);
// echo $this->formHidden($form->get('idAlbum'));
// echo $this->formHidden($form->get('nickName'));
// echo $this->formRow($form->get('nombre'));
// echo $this->formRow($form->get('descripcion'));
// echo $this->formSubmit($form->get('submit'));
echo $this->formCollection($form);
echo $this->form()->closeTag();

//if(isset($this->form)){
//    var_dump($this->form);
//}
if(isset($this->imagen)){
    var_dump($this->imagen);
}
if(isset($this->imagenxalbum)){
    var_dump($this->imagenxalbum);
}