<?php

 $title = 'Editar album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
  $form->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('idAlbum'));
 echo $this->formHidden($form->get('nickName'));
 echo $this->formRow($form->get('nombre'));
 echo $this->formRow($form->get('descripcion'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();

 
 echo '<br /><br />'.var_dump($this->mensaje);
