<a href="<?php echo $this->url('album', array('action' => 'add')) ?>">Crear nuevo album</a>

<table class="table">
    <tr>
        <th>
            Titulo
        </th>
        <th>
            Descripción
        </th>
        <th>
            Usuario
        </th>
        <th>
            Opciones
        </th>
    </tr>
    <?php foreach ($this->albumes as $album) { ?>

        <tr>
            <td><?php echo $album->getNombre() ?></td>
            <td><?php echo $album->getDescripcion() ?></td>
            <td><?php echo $album->getNickName() ?></td>
            <td>
                <a href="<?php echo $this->url('imagen', array('action' => 'index', 'id' => $album->getIdAlbum(), 'nombre' => $album->getNombre())) ?>">Ver</a>
                <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->getIdAlbum())) ?>">Editar</a>
                <a href="<?php echo $this->url('album', array('action' => 'delete', "id" => $album->getIdAlbum())) ?>">Eliminar</a>
            </td>
        </tr>


    <?php } ?>

</table>