<?php //echo $this->partial('flash-message'); ?>
 
<?php
$form = $this->loginForm;
$form->prepare();
echo $this->form()->openTag($form);
?>
<table>
  <tr>
    <td><?php echo $this->formlabel($form->get('nickName'));?></td>
    <td><?php echo $this->formElement($form->get('nickName')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('nickName'));?></span></td>
  </tr>
  <tr>
    <td><?php echo $this->formlabel($form->get('contrasena'));?></td>
    <td><?php echo $this->formElement($form->get('contrasena')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('contrasena'));?></span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
    <?php
        echo $this->formRow($form->get('loginCsrf'));
        echo $this->formElement($form->get('submit'));
    ?>
    </td>
  </tr>
</table>
<?php
echo $this->form()->closeTag($form);
?>